- name: Build release APK
  run: ./gradlew assembleRelease
- name: Create GitHub Release
  uses: softprops/action-gh-release@v1
  if: startsWith(github.ref, 'refs/tags/')
  with:
    files: app/build/outputs/apk/release/app-release-unsigned.apk
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
